# Generated by Django 4.1.3 on 2022-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='Тэг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.article'),
        ),
    ]
